### ISSUE TITLE
how with esri

### ISSUE THREAD

**Issue by vxpert** [spatialagent001/BlogExamples#1]
great thanks.. you have done this with leaflet but how we can use geojson data to fill dgrid and esri map instead of leaflet.....

**Comment by spatialagent001** [comment]
No problem.  I'm glad you found the blog useful.  Standard geojson isn't really supported yet with esri's api's, they have their own json format.  But I hear they will release one soon.  Currently I know of two options, one is to use <a href="https://github.com/esri/koop">koop</a> to convert for data to an esri json format before you load the data into a map.  The other is to use the <a href="https://github.com/esri/terraformer">terraformer</a> js library as a intermediate data parser.  Both are well documented on git hub.  Once you have the data in a format esri's map works with you can do the dgrid thing or use their new <a href="https://developers.arcgis.com/javascript/jssamples/featuretable.html">featuretable</a> class which is a wrapper to dGrid.  I'll make a note to blog about this topic in the future

**Comment by vxpert** [comment]
Thanks for reply.. Yes checked those too.. And i found one other way... using feature collection to use esri instead of leaflet
https://developers.arcgis.com/javascript/jssamples/fl_featureCollection.html

i formatted my service according to esri format and the passed it to feature collection.. it works worth for me... As of my requirement i am using Polyline instead of point.

https://developers.arcgis.com/javascript/jsapi/polyline.html

https://developers.arcgis.com/javascript/jsapi/polyline-amd.html

regards
